[build]
  command = "npx prisma generate && next build"
  publish = ".next"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[scheduled]]
  function = "sendReminders"
  cron = "0 4 * * *"
